services:
  actualimporter:
    image: actualimporter:latest
    build: .
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
      ACTUAL_SERVER_URL: ${ACTUAL_SERVER_URL:-}
      ACTUAL_PASSWORD: ${ACTUAL_PASSWORD:-}
      ACTUAL_BUDGET_ID: ${ACTUAL_BUDGET_ID:-}
      MOCK_ACTUAL: ${MOCK_ACTUAL:-false}