services:
  actualimporter:
    build: .
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
      ACTUAL_SERVER_URL: ${ACTUAL_SERVER_URL:-}
      ACTUAL_PASSWORD: ${ACTUAL_PASSWORD:-}
      ACTUAL_BUDGET_ID: ${ACTUAL_BUDGET_ID:-}
      ACTUAL_ACCOUNTS_ENDPOINT: ${ACTUAL_ACCOUNTS_ENDPOINT:-/api/accounts}
      ACTUAL_IMPORT_ENDPOINT: ${ACTUAL_IMPORT_ENDPOINT:-/api/import-transactions}
      MOCK_ACTUAL: ${MOCK_ACTUAL:-false}